[CmdletBinding()]
param(
  [Parameter(Mandatory)]
  [ValidateSet("Detect", "GenerateLocal", "Generate", "Validate")]
  [string]$Mode,

  [ValidateSet("auto", "tauri", "node", "go", "python", "rust", "dotnet", "java", "cmake", "flutter", "android", "electron", "docker")]
  [string]$ProjectType = "auto",

  [string]$RepositoryRoot = (Get-Location).Path,

  [string]$ConfigPath = ".codex-release.json",

  [string]$WorkflowPath = ".github/workflows/release.yml",

  [ValidateSet("Stop", "CreateSeparate", "ReuseCompatible")]
  [string]$ExistingWorkflowPolicy = "Stop",

  [string]$SeparateWorkflowPath = ".github/workflows/auto-release.yml"
)

$ErrorActionPreference = "Stop"
$script:GeneratorName = "auto-release"
$script:LegacyGeneratorNames = @("project-release-automator")
$script:WorkflowMarker = "# Generated by Auto Release"
$script:LegacyWorkflowMarkers = @("# Generated by Project Release Automator")
$script:ResolvedRepositoryRoot = $null

function Get-OptionalProperty($Object, [string]$Name, $Default = $null) {
  if ($null -eq $Object) { return $Default }
  $property = $Object.PSObject.Properties[$Name]
  if ($null -eq $property) { return $Default }
  return $property.Value
}

function Get-RequiredProperty($Object, [string]$Name, [string]$Context) {
  $value = Get-OptionalProperty $Object $Name
  if ($null -eq $value -or ($value -is [string] -and [string]::IsNullOrWhiteSpace($value))) {
    throw "Missing required config field: $Context.$Name"
  }
  return $value
}

function Get-NormalizedPath([string]$Path) {
  return [IO.Path]::GetFullPath($Path).TrimEnd(
    [IO.Path]::DirectorySeparatorChar,
    [IO.Path]::AltDirectorySeparatorChar
  )
}

function Resolve-RepositoryFile([string]$RelativePath) {
  if ([IO.Path]::IsPathRooted($RelativePath)) {
    throw "Generated path must be relative: $RelativePath"
  }
  $fullPath = Get-NormalizedPath (Join-Path $script:ResolvedRepositoryRoot $RelativePath)
  $prefix = $script:ResolvedRepositoryRoot + [IO.Path]::DirectorySeparatorChar
  if (-not $fullPath.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Generated path escapes repository root: $RelativePath"
  }
  return $fullPath
}

function Read-JsonFile([string]$Path, [string]$Label) {
  try {
    return Get-Content -Raw -Encoding UTF8 -LiteralPath $Path | ConvertFrom-Json
  }
  catch {
    throw "$Label is not valid JSON: $Path. $($_.Exception.Message)"
  }
}

function Get-GitValue([string[]]$Arguments) {
  $output = & git -C $script:ResolvedRepositoryRoot @Arguments 2>$null
  if ($LASTEXITCODE -ne 0) { return $null }
  return (($output | Out-String).Trim())
}

function Get-RepositoryDefaults {
  $branch = Get-GitValue @("branch", "--show-current")
  if (-not $branch) { $branch = "main" }
  $remotes = @((Get-GitValue @("remote")) -split "`r?`n" | Where-Object { $_ })
  $remote = if ($remotes -contains "origin") { "origin" } elseif ($remotes.Count -gt 0) { $remotes[0] } else { "origin" }
  return [pscustomobject]@{ Branch = $branch; Remote = $remote }
}

function Get-PackageManager {
  $name = "npm"
  $install = "npm install"
  $setup = ""
  if (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "pnpm-lock.yaml")) {
    $name = "pnpm"
    $install = "pnpm install --frozen-lockfile"
    $setup = "      - name: Enable Corepack`n        run: corepack enable"
  }
  elseif (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "yarn.lock")) {
    $name = "yarn"
    $install = "yarn install --frozen-lockfile"
    $setup = "      - name: Enable Corepack`n        run: corepack enable"
  }
  elseif (
    (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "bun.lock")) -or
    (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "bun.lockb"))
  ) {
    $name = "bun"
    $install = "bun install --frozen-lockfile"
    $setup = "      - uses: oven-sh/setup-bun@v2"
  }
  elseif (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "package-lock.json")) {
    $install = "npm ci"
  }
  return [pscustomobject]@{ Name = $name; Install = $install; WorkflowSetup = $setup }
}

function Get-PackageCommand([string]$Manager, [string]$ScriptName) {
  if ($Manager -eq "npm") { return "npm run $ScriptName" }
  if ($Manager -eq "pnpm") { return "pnpm run $ScriptName" }
  if ($Manager -eq "yarn") { return "yarn $ScriptName" }
  return "bun run $ScriptName"
}

function Get-TauriLocalBuildCommand([string]$Manager) {
  $command = Get-PackageCommand $Manager "tauri build"
  if ($Manager -in @("npm", "pnpm")) { return "$command -- --no-bundle" }
  return "$command --no-bundle"
}

function Test-PackageScript($Package, [string]$Name) {
  $scripts = Get-OptionalProperty $Package "scripts"
  $value = [string](Get-OptionalProperty $scripts $Name "")
  if (-not $value) { return $false }
  if ($Name -eq "test" -and $value -match "no test specified") { return $false }
  return $true
}

function ConvertTo-ArtifactStem([string]$Name) {
  $stem = $Name.ToLowerInvariant() -replace '^@', '' -replace '[\\/]+', '-' -replace '[^a-z0-9._-]+', '-'
  $stem = $stem.Trim('-', '.')
  if (-not $stem) { return "release" }
  return $stem
}

function Get-InferredVersion {
  $versionFile = Join-Path $script:ResolvedRepositoryRoot "VERSION"
  if (Test-Path -LiteralPath $versionFile -PathType Leaf) {
    $value = ([IO.File]::ReadAllText($versionFile)).Trim()
    if ($value -notmatch '^\d+\.\d+\.\d+$') {
      throw "VERSION must contain a stable semantic version"
    }
    return $value
  }
  $tags = @(Get-GitValue @("tag", "--list", "v[0-9]*", "--sort=-v:refname") -split "`r?`n")
  foreach ($tag in $tags) {
    if ($tag -match '^v(?<version>\d+\.\d+\.\d+)$') { return $Matches.version }
  }
  return "0.1.0"
}

function Get-RelativeRepositoryPath([string]$Path) {
  $fullPath = Get-NormalizedPath $Path
  $prefix = $script:ResolvedRepositoryRoot + [IO.Path]::DirectorySeparatorChar
  if (-not $fullPath.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Path is outside repository root: $Path"
  }
  return $fullPath.Substring($prefix.Length).Replace("\", "/")
}

function Get-XmlDirectValue($Document, [string]$Name) {
  $node = @($Document.DocumentElement.ChildNodes | Where-Object { $_.LocalName -eq $Name }) | Select-Object -First 1
  if ($node) { return [string]$node.InnerText }
  return $null
}

function Get-XmlDescendantValue($Document, [string]$Name) {
  $node = $Document.SelectSingleNode("//*[local-name()='$Name']")
  if ($node) { return [string]$node.InnerText }
  return $null
}

function Get-DotNetProjectFiles {
  $files = @()
  $excluded = @(".git", ".venv", "bin", "build", "dist", "node_modules", "obj", "target", "vendor", "venv")
  $queue = New-Object 'Collections.Generic.Queue[string]'
  $queue.Enqueue($script:ResolvedRepositoryRoot)
  while ($queue.Count -gt 0) {
    $directory = $queue.Dequeue()
    foreach ($file in Get-ChildItem -LiteralPath $directory -File) {
      if ($file.Extension -in @(".csproj", ".fsproj", ".vbproj")) { $files += $file }
    }
    foreach ($child in Get-ChildItem -LiteralPath $directory -Directory) {
      if ($child.Name -notin $excluded -and -not ($child.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        $queue.Enqueue($child.FullName)
      }
    }
  }
  return @($files)
}

function Get-AndroidApplicationModules {
  $modules = @()
  foreach ($directory in Get-ChildItem -LiteralPath $script:ResolvedRepositoryRoot -Directory) {
    foreach ($name in @("build.gradle.kts", "build.gradle")) {
      $candidate = Join-Path $directory.FullName $name
      if (Test-Path -LiteralPath $candidate -PathType Leaf) {
        $content = [IO.File]::ReadAllText($candidate)
        if ($content -match 'com\.android\.application') {
          $modules += [pscustomobject]@{
            Directory = Get-RelativeRepositoryPath $directory.FullName
            BuildFile = Get-RelativeRepositoryPath $candidate
            Content = $content
          }
        }
      }
    }
  }
  return @($modules)
}

function Test-ElectronPackage($Package) {
  if (-not $Package) { return $false }
  $dependencies = Get-OptionalProperty $Package "dependencies"
  $devDependencies = Get-OptionalProperty $Package "devDependencies"
  return $null -ne (Get-OptionalProperty $dependencies "electron") -or
    $null -ne (Get-OptionalProperty $devDependencies "electron")
}

function Get-ProjectProfile([string]$RequestedType) {
  $tauriConfigPath = Join-Path $script:ResolvedRepositoryRoot "src-tauri\tauri.conf.json"
  $tauriCargoPath = Join-Path $script:ResolvedRepositoryRoot "src-tauri\Cargo.toml"
  $packagePath = Join-Path $script:ResolvedRepositoryRoot "package.json"
  $goModPath = Join-Path $script:ResolvedRepositoryRoot "go.mod"
  $pythonPath = Join-Path $script:ResolvedRepositoryRoot "pyproject.toml"
  $cargoPath = Join-Path $script:ResolvedRepositoryRoot "Cargo.toml"
  $mavenPath = Join-Path $script:ResolvedRepositoryRoot "pom.xml"
  $gradlePath = Join-Path $script:ResolvedRepositoryRoot "build.gradle"
  $gradleKtsPath = Join-Path $script:ResolvedRepositoryRoot "build.gradle.kts"
  $flutterPath = Join-Path $script:ResolvedRepositoryRoot "pubspec.yaml"
  $cmakePath = Join-Path $script:ResolvedRepositoryRoot "CMakeLists.txt"
  $dockerPath = Join-Path $script:ResolvedRepositoryRoot "Dockerfile"
  $hasTauri = (Test-Path -LiteralPath $tauriConfigPath -PathType Leaf) -and (Test-Path -LiteralPath $tauriCargoPath -PathType Leaf)
  $hasNode = Test-Path -LiteralPath $packagePath -PathType Leaf
  $packageManifest = if ($hasNode) { Read-JsonFile $packagePath "package.json" } else { $null }
  $hasElectron = Test-ElectronPackage $packageManifest
  $hasGo = Test-Path -LiteralPath $goModPath -PathType Leaf
  $hasPython = Test-Path -LiteralPath $pythonPath -PathType Leaf
  $hasRust = Test-Path -LiteralPath $cargoPath -PathType Leaf
  $dotnetProjects = @(Get-DotNetProjectFiles)
  $dotnetProject = if ($dotnetProjects.Count -eq 1) { $dotnetProjects[0] } else { $null }
  $hasDotNet = $dotnetProjects.Count -gt 0
  $hasJava = (Test-Path -LiteralPath $mavenPath -PathType Leaf) -or
    (Test-Path -LiteralPath $gradlePath -PathType Leaf) -or
    (Test-Path -LiteralPath $gradleKtsPath -PathType Leaf)
  $androidModules = @(Get-AndroidApplicationModules)
  $hasGradleWrapper = Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "gradlew") -PathType Leaf
  $hasAndroid = $androidModules.Count -gt 0 -and $hasGradleWrapper
  $hasFlutter = Test-Path -LiteralPath $flutterPath -PathType Leaf
  $hasCMake = Test-Path -LiteralPath $cmakePath -PathType Leaf
  $hasDocker = Test-Path -LiteralPath $dockerPath -PathType Leaf

  $detectedType = $RequestedType
  if ($RequestedType -eq "auto") {
    if ($hasTauri) { $detectedType = "tauri" }
    elseif ($hasFlutter) { $detectedType = "flutter" }
    elseif ($hasAndroid) { $detectedType = "android" }
    elseif ($hasElectron) { $detectedType = "electron" }
    else {
      $candidates = @()
      if ($hasNode -and -not $hasElectron) { $candidates += "node" }
      if ($hasGo) { $candidates += "go" }
      if ($hasPython) { $candidates += "python" }
      if ($hasRust) { $candidates += "rust" }
      if ($hasDotNet) { $candidates += "dotnet" }
      if ($hasJava) { $candidates += "java" }
      if ($hasCMake) { $candidates += "cmake" }
      if ($hasDocker -and $candidates.Count -eq 0) { $candidates += "docker" }
      if ($candidates.Count -gt 1) {
        throw "Project detection is ambiguous: $($candidates -join ', '); use -ProjectType explicitly"
      }
      if ($candidates.Count -eq 0) {
        throw "Unsupported project: no supported release manifest was found"
      }
      $detectedType = $candidates[0]
    }
  }
  if ($detectedType -eq "tauri" -and -not $hasTauri) { throw "Tauri detection requires src-tauri/tauri.conf.json and src-tauri/Cargo.toml" }
  if ($detectedType -eq "node" -and -not $hasNode) { throw "Node.js detection requires package.json" }
  if ($detectedType -eq "go" -and -not $hasGo) { throw "Go detection requires go.mod" }
  if ($detectedType -eq "python" -and -not $hasPython) { throw "Python detection requires pyproject.toml" }
  if ($detectedType -eq "rust" -and -not $hasRust) { throw "Rust detection requires Cargo.toml" }
  if ($detectedType -eq "dotnet" -and $dotnetProjects.Count -ne 1) { throw ".NET detection requires exactly one project file" }
  if ($detectedType -eq "java" -and -not $hasJava) { throw "Java detection requires pom.xml or build.gradle" }
  if ($detectedType -eq "cmake" -and -not $hasCMake) { throw "CMake detection requires CMakeLists.txt" }
  if ($detectedType -eq "flutter" -and -not $hasFlutter) { throw "Flutter detection requires pubspec.yaml" }
  if ($detectedType -eq "android" -and ($androidModules.Count -ne 1 -or -not $hasGradleWrapper)) { throw "Android detection requires one application module and the Gradle wrapper" }
  if ($detectedType -eq "electron" -and -not $hasElectron) { throw "Electron detection requires the electron package dependency" }
  if ($detectedType -eq "docker" -and -not $hasDocker) { throw "Docker detection requires Dockerfile" }

  $fallbackName = Split-Path -Leaf $script:ResolvedRepositoryRoot
  if ($detectedType -eq "flutter") {
    $content = [IO.File]::ReadAllText($flutterPath)
    $nameMatch = [regex]::Match($content, '(?m)^name:\s*(?<name>[A-Za-z0-9_.-]+)\s*$')
    $versionMatch = [regex]::Match($content, '(?m)^version:\s*(?<version>\d+\.\d+\.\d+)(?:\+\d+)?\s*$')
    if (-not $nameMatch.Success -or -not $versionMatch.Success) { throw "pubspec.yaml must contain a name and stable semantic version" }
    return [pscustomobject]@{
      ProjectType = "flutter"; ProjectName = $nameMatch.Groups["name"].Value; Version = $versionMatch.Groups["version"].Value
      VersionSource = "pubspec.yaml"; PackageManager = "flutter"; Package = $null; Manager = $null; BuildPath = $null
      VersionReadPattern = '(?m)^version:\s*(?<version>\d+\.\d+\.\d+)(?:\+\d+)?\s*$'
      VersionUpdatePattern = '(?m)^(version:\s*)\d+\.\d+\.\d+(?:\+\d+)?\s*$'
      HasTests = (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "test") -PathType Container)
    }
  }

  if ($detectedType -eq "android") {
    $module = $androidModules[0]
    $versionMatch = [regex]::Match($module.Content, '(?m)^\s*versionName\s*(?:=\s*)?["''](?<version>\d+\.\d+\.\d+)["'']')
    if (-not $versionMatch.Success) { throw "Android application module must contain a static semantic versionName" }
    $settingsPath = @("settings.gradle.kts", "settings.gradle") | ForEach-Object { Join-Path $script:ResolvedRepositoryRoot $_ } | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
    $name = $fallbackName
    if ($settingsPath) {
      $settings = [IO.File]::ReadAllText($settingsPath)
      $nameMatch = [regex]::Match($settings, '(?m)^\s*rootProject\.name\s*=\s*["''](?<name>[^"'']+)["'']')
      if ($nameMatch.Success) { $name = $nameMatch.Groups["name"].Value }
    }
    $localBuild = if (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "gradlew.bat")) { ".\gradlew.bat test assembleRelease bundleRelease --no-daemon" } else { "gradle test assembleRelease bundleRelease --no-daemon" }
    return [pscustomobject]@{
      ProjectType = "android"; ProjectName = $name; Version = $versionMatch.Groups["version"].Value
      VersionSource = $module.BuildFile; PackageManager = "gradle"; Package = $null; Manager = $null; BuildPath = $module.Directory
      VersionReadPattern = '(?m)^\s*versionName\s*(?:=\s*)?["''](?<version>\d+\.\d+\.\d+)["'']'
      VersionUpdatePattern = '(?m)^(\s*versionName\s*(?:=\s*)?["''])\d+\.\d+\.\d+(["''])'
      AndroidLocalBuild = $localBuild
    }
  }

  if ($detectedType -eq "electron") {
    $name = [string](Get-OptionalProperty $packageManifest "productName" (Get-OptionalProperty $packageManifest "name" $fallbackName))
    $version = [string](Get-OptionalProperty $packageManifest "version" "")
    if ($version -notmatch '^\d+\.\d+\.\d+$') { throw "Electron package.json must contain a stable semantic version" }
    $scripts = Get-OptionalProperty $packageManifest "scripts"
    $buildScript = @("dist", "release", "package", "make", "build") | Where-Object { Test-PackageScript $packageManifest $_ } | Select-Object -First 1
    if (-not $buildScript) { throw "Electron package.json must define a dist, release, package, make, or build script" }
    $manager = Get-PackageManager
    $buildConfig = Get-OptionalProperty $packageManifest "build"
    $directories = Get-OptionalProperty $buildConfig "directories"
    $output = [string](Get-OptionalProperty $directories "output" "dist")
    if ([IO.Path]::IsPathRooted($output) -or $output -match '(^|[\\/])\.\.([\\/]|$)' -or $output -notmatch '^[A-Za-z0-9._/\\-]+$') {
      throw "Electron output directory must be a safe repository-relative path"
    }
    return [pscustomobject]@{
      ProjectType = "electron"; ProjectName = $name; Version = $version; VersionSource = "package.json"
      PackageManager = $manager.Name; Package = $packageManifest; Manager = $manager; BuildPath = $null
      ElectronBuildCommand = Get-PackageCommand $manager.Name $buildScript; ElectronOutput = $output
    }
  }

  if ($detectedType -eq "cmake") {
    $content = [IO.File]::ReadAllText($cmakePath)
    $projectMatch = [regex]::Match($content, '(?is)\bproject\s*\(\s*(?<name>[A-Za-z0-9_.+-]+)(?:(?!\)).)*\)')
    if (-not $projectMatch.Success) { throw "CMakeLists.txt must contain a project declaration" }
    $versionMatch = [regex]::Match($projectMatch.Value, '(?is)\bVERSION\s+(?<version>\d+\.\d+\.\d+)')
    $targets = @([regex]::Matches($content, '(?im)^\s*add_executable\s*\(\s*(?<name>[A-Za-z0-9_.+-]+)') | ForEach-Object { $_.Groups["name"].Value } | Sort-Object -Unique)
    if ($targets.Count -ne 1) { throw "CMake generation requires exactly one add_executable target" }
    $needsVersionFile = -not $versionMatch.Success
    return [pscustomobject]@{
      ProjectType = "cmake"; ProjectName = $projectMatch.Groups["name"].Value; Version = if ($needsVersionFile) { Get-InferredVersion } else { $versionMatch.Groups["version"].Value }
      VersionSource = if ($needsVersionFile) { "VERSION" } else { "CMakeLists.txt" }
      PackageManager = "cmake"; Package = $null; Manager = $null; BuildPath = $null
      CMakeTarget = $targets[0]; NeedsVersionFile = $needsVersionFile
    }
  }

  if ($detectedType -eq "docker") {
    $dockerContent = [IO.File]::ReadAllText($dockerPath)
    $titleMatch = [regex]::Match($dockerContent, '(?im)^\s*LABEL\s+org\.opencontainers\.image\.title\s*=\s*["'']?(?<name>[^"''\s]+)')
    $name = if ($titleMatch.Success) { $titleMatch.Groups["name"].Value } else { $fallbackName }
    return [pscustomobject]@{
      ProjectType = "docker"; ProjectName = $name; Version = Get-InferredVersion; VersionSource = "VERSION"
      PackageManager = "docker"; Package = $null; Manager = $null; BuildPath = "Dockerfile"
      NeedsVersionFile = -not (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "VERSION"))
    }
  }
  if ($detectedType -eq "tauri") {
    $tauri = Read-JsonFile $tauriConfigPath "Tauri config"
    $tauriPackage = Get-OptionalProperty $tauri "package"
    $name = [string](Get-OptionalProperty $tauri "productName" (Get-OptionalProperty $tauriPackage "productName" $fallbackName))
    $version = [string](Get-OptionalProperty $tauri "version" (Get-OptionalProperty $tauriPackage "version" ""))
    if ($version -notmatch '^\d+\.\d+\.\d+$') { throw "Tauri config must contain a stable semantic version" }
    $package = $null
    if ($hasNode) { $package = Read-JsonFile $packagePath "package.json" }
    $manager = Get-PackageManager
    return [pscustomobject]@{
      ProjectType = "tauri"; ProjectName = $name; Version = $version
      VersionSource = "src-tauri/tauri.conf.json"; PackageManager = if ($hasNode) { $manager.Name } else { $null }
      Package = $package; Manager = $manager; BuildPath = $null
    }
  }

  if ($detectedType -eq "node") {
    $package = Read-JsonFile $packagePath "package.json"
    $name = [string](Get-OptionalProperty $package "name" $fallbackName)
    $version = [string](Get-OptionalProperty $package "version" "")
    if ($version -notmatch '^\d+\.\d+\.\d+$') { throw "package.json must contain a stable semantic version" }
    $manager = Get-PackageManager
    return [pscustomobject]@{
      ProjectType = "node"; ProjectName = $name; Version = $version
      VersionSource = "package.json"; PackageManager = $manager.Name
      Package = $package; Manager = $manager; BuildPath = $null
    }
  }

  if ($detectedType -eq "go") {
    $goMod = [IO.File]::ReadAllText($goModPath)
    $moduleMatch = [regex]::Match($goMod, '(?m)^module\s+(?<module>\S+)\s*$')
    if (-not $moduleMatch.Success) { throw "go.mod does not contain a module directive" }
    $module = $moduleMatch.Groups["module"].Value
    $name = ($module -split '/')[(-1)]
    $namedCommand = Join-Path $script:ResolvedRepositoryRoot ("cmd\" + $name)
    $buildPath = if (Test-Path -LiteralPath $namedCommand -PathType Container) { "./cmd/$name" } else { "." }
    return [pscustomobject]@{
      ProjectType = "go"; ProjectName = $name; Version = Get-InferredVersion
      VersionSource = "VERSION"; PackageManager = $null; Package = $null
      Manager = $null; BuildPath = $buildPath; NeedsVersionFile = -not (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "VERSION"))
    }
  }

  if ($detectedType -eq "python") {
    $content = [IO.File]::ReadAllText($pythonPath)
    $sections = @(
      @{ Name = "project"; Prefix = '(?ms)^\[project\]\s*(?:(?!^\[).)*?' },
      @{ Name = "tool.poetry"; Prefix = '(?ms)^\[tool\.poetry\]\s*(?:(?!^\[).)*?' }
    )
    $selected = $null
    foreach ($section in $sections) {
      $nameMatch = [regex]::Match($content, $section.Prefix + '^name\s*=\s*["''](?<name>[^"'']+)["'']')
      $versionMatch = [regex]::Match($content, $section.Prefix + '^version\s*=\s*["''](?<version>\d+\.\d+\.\d+)["'']')
      if ($nameMatch.Success -and $versionMatch.Success) {
        $selected = [pscustomobject]@{ Name = $nameMatch.Groups["name"].Value; Version = $versionMatch.Groups["version"].Value; Section = $section.Prefix }
        break
      }
    }
    if (-not $selected) { throw "pyproject.toml must contain a static PEP 621 or Poetry name and semantic version" }
    $pythonManager = if (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "uv.lock")) { "uv" }
      elseif (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "poetry.lock")) { "poetry" }
      else { "pip" }
    return [pscustomobject]@{
      ProjectType = "python"; ProjectName = $selected.Name; Version = $selected.Version
      VersionSource = "pyproject.toml"; PackageManager = $pythonManager; Package = $null; Manager = $null; BuildPath = $null
      VersionReadPattern = $selected.Section + '^version\s*=\s*["''](?<version>\d+\.\d+\.\d+)["'']'
      VersionUpdatePattern = '(' + $selected.Section + '^version\s*=\s*["''])\d+\.\d+\.\d+(["''])'
      HasTests = (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "tests") -PathType Container)
    }
  }

  if ($detectedType -eq "rust") {
    $content = [IO.File]::ReadAllText($cargoPath)
    $nameMatch = [regex]::Match($content, '(?ms)^\[package\]\s*(?:(?!^\[).)*?^name\s*=\s*"(?<name>[^"]+)"')
    $versionMatch = [regex]::Match($content, '(?ms)^\[package\]\s*(?:(?!^\[).)*?^version\s*=\s*"(?<version>\d+\.\d+\.\d+)"')
    if (-not $nameMatch.Success -or -not $versionMatch.Success) { throw "Cargo.toml must contain a non-workspace package name and stable semantic version" }
    return [pscustomobject]@{
      ProjectType = "rust"; ProjectName = $nameMatch.Groups["name"].Value; Version = $versionMatch.Groups["version"].Value
      VersionSource = "Cargo.toml"; PackageManager = "cargo"; Package = $null; Manager = $null; BuildPath = $null
    }
  }

  if ($detectedType -eq "dotnet") {
    $projectContent = [IO.File]::ReadAllText($dotnetProject.FullName)
    try { [xml]$projectXml = $projectContent } catch { throw ".NET project file is invalid XML: $($dotnetProject.FullName)" }
    $name = Get-XmlDescendantValue $projectXml "PackageId"
    if (-not $name) { $name = Get-XmlDescendantValue $projectXml "AssemblyName" }
    if (-not $name) { $name = [IO.Path]::GetFileNameWithoutExtension($dotnetProject.Name) }
    $projectRelative = Get-RelativeRepositoryPath $dotnetProject.FullName
    $versionElement = if ($projectContent -match '<Version>\s*\d+\.\d+\.\d+\s*</Version>') { "Version" }
      elseif ($projectContent -match '<VersionPrefix>\s*\d+\.\d+\.\d+\s*</VersionPrefix>') { "VersionPrefix" }
      else { $null }
    $needsVersionFile = $null -eq $versionElement
    $version = if ($needsVersionFile) { Get-InferredVersion }
      else { [regex]::Match($projectContent, "<$versionElement>\s*(?<version>\d+\.\d+\.\d+)\s*</$versionElement>").Groups["version"].Value }
    $targetFramework = Get-XmlDescendantValue $projectXml "TargetFramework"
    $frameworkMatch = [regex]::Match([string]$targetFramework, '^net(?<major>\d+)\.(?<minor>\d+)')
    $sdkVersion = if ($frameworkMatch.Success) { "$($frameworkMatch.Groups['major'].Value).$($frameworkMatch.Groups['minor'].Value).x" } else { "8.0.x" }
    return [pscustomobject]@{
      ProjectType = "dotnet"; ProjectName = $name; Version = $version
      VersionSource = if ($needsVersionFile) { "VERSION" } else { $projectRelative }
      PackageManager = "dotnet"; Package = $null; Manager = $null; BuildPath = $projectRelative
      VersionElement = $versionElement; NeedsVersionFile = $needsVersionFile; DotNetVersion = $sdkVersion
    }
  }

  $hasMaven = Test-Path -LiteralPath $mavenPath -PathType Leaf
  $hasGradle = (Test-Path -LiteralPath $gradlePath -PathType Leaf) -or (Test-Path -LiteralPath $gradleKtsPath -PathType Leaf)
  if ($hasMaven -and $hasGradle) { throw "Both Maven and Gradle manifests exist; use a repository-specific config" }
  if ($hasMaven) {
    $content = [IO.File]::ReadAllText($mavenPath)
    try { [xml]$pom = $content } catch { throw "pom.xml is invalid XML" }
    $artifactId = Get-XmlDirectValue $pom "artifactId"
    $version = Get-XmlDirectValue $pom "version"
    if (-not $artifactId -or $version -notmatch '^\d+\.\d+\.\d+$') { throw "pom.xml must contain a direct artifactId and stable semantic version" }
    $escapedArtifact = [regex]::Escape($artifactId)
    $readPattern = '(?ms)<artifactId>\s*' + $escapedArtifact + '\s*</artifactId>\s*<version>\s*(?<version>\d+\.\d+\.\d+)\s*</version>'
    $updatePattern = '(?ms)(<artifactId>\s*' + $escapedArtifact + '\s*</artifactId>\s*<version>\s*)\d+\.\d+\.\d+(\s*</version>)'
    $localBuild = if (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "mvnw.cmd")) { ".\mvnw.cmd -B test package" } else { "mvn -B test package" }
    $workflowBuild = if (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "mvnw")) { "./mvnw -B test package" } else { "mvn -B test package" }
    return [pscustomobject]@{
      ProjectType = "java"; ProjectName = $artifactId; Version = $version; VersionSource = "pom.xml"
      PackageManager = "maven"; Package = $null; Manager = $null; BuildPath = $null
      VersionReadPattern = $readPattern; VersionUpdatePattern = $updatePattern
      JavaLocalBuild = $localBuild; JavaWorkflowBuild = $workflowBuild; JavaArtifactDirectory = "target"; JavaCache = "maven"
    }
  }

  $gradleFile = if (Test-Path -LiteralPath $gradleKtsPath -PathType Leaf) { $gradleKtsPath } else { $gradlePath }
  $content = [IO.File]::ReadAllText($gradleFile)
  $versionMatch = [regex]::Match($content, '(?m)^\s*version\s*=\s*["''](?<version>\d+\.\d+\.\d+)["'']')
  if (-not $versionMatch.Success) { throw "Gradle build file must contain a static stable semantic version" }
  $settingsPath = @("settings.gradle.kts", "settings.gradle") | ForEach-Object { Join-Path $script:ResolvedRepositoryRoot $_ } | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
  $name = $fallbackName
  if ($settingsPath) {
    $settings = [IO.File]::ReadAllText($settingsPath)
    $nameMatch = [regex]::Match($settings, '(?m)^\s*rootProject\.name\s*=\s*["''](?<name>[^"'']+)["'']')
    if ($nameMatch.Success) { $name = $nameMatch.Groups["name"].Value }
  }
  $relativeGradle = Get-RelativeRepositoryPath $gradleFile
  $localBuild = if (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "gradlew.bat")) { ".\gradlew.bat test build --no-daemon" } else { "gradle test build --no-daemon" }
  $workflowBuild = if (Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot "gradlew")) { "./gradlew test build --no-daemon" } else { "gradle test build --no-daemon" }
  return [pscustomobject]@{
    ProjectType = "java"; ProjectName = $name; Version = $versionMatch.Groups["version"].Value; VersionSource = $relativeGradle
    PackageManager = "gradle"; Package = $null; Manager = $null; BuildPath = $null
    VersionReadPattern = '(?m)^\s*version\s*=\s*["''](?<version>\d+\.\d+\.\d+)["'']'
    VersionUpdatePattern = '(?m)^(\s*version\s*=\s*["''])\d+\.\d+\.\d+(["''])'
    JavaLocalBuild = $localBuild; JavaWorkflowBuild = $workflowBuild; JavaArtifactDirectory = "build/libs"; JavaCache = "gradle"
  }
}

function New-VersionUpdate([string]$Path, [string]$Pattern, [string]$Replacement) {
  return [pscustomobject][ordered]@{
    path = $Path
    pattern = $Pattern
    replacement = $Replacement
    expectedMatches = 1
  }
}

function Add-ExistingVersionUpdate([ref]$Updates, [string]$RelativePath, [string]$Pattern, [string]$Replacement) {
  $path = Join-Path $script:ResolvedRepositoryRoot $RelativePath
  if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { return }
  $count = ([regex]::new($Pattern)).Matches([IO.File]::ReadAllText($path)).Count
  if ($count -gt 1) { throw "Version pattern is ambiguous in ${RelativePath}: $count matches" }
  if ($count -eq 1) { $Updates.Value += New-VersionUpdate $RelativePath $Pattern $Replacement }
}

function Get-ReleaseNotesConfig {
  $heading =
    "## " +
    ([char]0x66F4).ToString() +
    ([char]0x65B0).ToString() +
    ([char]0x5185).ToString() +
    ([char]0x5BB9).ToString()
  return [pscustomobject][ordered]@{
    heading = $heading
    minItems = 2
    maxItems = 6
    requireChinese = $true
  }
}

function Get-WorkflowConfig {
  return [pscustomobject][ordered]@{
    name = "Release"
    event = "push"
    findTimeoutSeconds = 120
    waitTimeoutMinutes = 90
  }
}

function Get-RequiredAssets([string]$Type, [string]$Stem) {
  if ($Type -eq "node") {
    return @([pscustomobject][ordered]@{ pattern = "(?i)^$([regex]::Escape($Stem))-\d+\.\d+\.\d+\.tgz$"; label = "npm package" })
  }
  if ($Type -eq "go") {
    $names = @(
      "$Stem-windows-amd64.exe", "$Stem-windows-arm64.exe",
      "$Stem-linux-amd64", "$Stem-linux-arm64",
      "$Stem-darwin-amd64", "$Stem-darwin-arm64"
    )
    return @($names | ForEach-Object {
      [pscustomobject][ordered]@{ pattern = "(?i)^$([regex]::Escape($_))$"; label = $_ }
    })
  }
  if ($Type -eq "python") {
    return @(
      [pscustomobject][ordered]@{ pattern = '(?i)^.+-\d+\.\d+\.\d+\.tar\.gz$'; label = "Python source distribution" },
      [pscustomobject][ordered]@{ pattern = '(?i)^.+-\d+\.\d+\.\d+-.+\.whl$'; label = "Python wheel" }
    )
  }
  if ($Type -eq "rust") {
    return @([pscustomobject][ordered]@{ pattern = "(?i)^$([regex]::Escape($Stem))-\d+\.\d+\.\d+\.crate$"; label = "Rust crate" })
  }
  if ($Type -eq "dotnet") {
    return @([pscustomobject][ordered]@{ pattern = "(?i)^$([regex]::Escape($Stem))\.\d+\.\d+\.\d+\.nupkg$"; label = ".NET NuGet package" })
  }
  if ($Type -eq "java") {
    return @([pscustomobject][ordered]@{ pattern = "(?i)^$([regex]::Escape($Stem))-\d+\.\d+\.\d+(?:-[^/]+)?\.jar$"; label = "Java package" })
  }
  if ($Type -eq "cmake" -or $Type -eq "electron") {
    $names = @(
      "$Stem-windows-x64.zip", "$Stem-windows-arm64.zip",
      "$Stem-linux-x64.zip", "$Stem-linux-arm64.zip",
      "$Stem-macos-x64.zip", "$Stem-macos-arm64.zip"
    )
    return @($names | ForEach-Object { [pscustomobject][ordered]@{ pattern = "(?i)^$([regex]::Escape($_))$"; label = $_ } })
  }
  if ($Type -eq "flutter") {
    $names = @(
      "$Stem-android-apk.apk", "$Stem-android-aab.aab", "$Stem-windows-x64.zip",
      "$Stem-linux-x64.tar.gz", "$Stem-macos-x64.zip", "$Stem-macos-arm64.zip", "$Stem-web.zip"
    )
    return @($names | ForEach-Object { [pscustomobject][ordered]@{ pattern = "(?i)^$([regex]::Escape($_))$"; label = $_ } })
  }
  if ($Type -eq "android") {
    return @(
      [pscustomobject][ordered]@{ pattern = "(?i)^$([regex]::Escape($Stem))-\d+\.\d+\.\d+\.apk$"; label = "Android APK" },
      [pscustomobject][ordered]@{ pattern = "(?i)^$([regex]::Escape($Stem))-\d+\.\d+\.\d+\.aab$"; label = "Android App Bundle" }
    )
  }
  if ($Type -eq "docker") {
    return @([pscustomobject][ordered]@{ pattern = "(?i)^$([regex]::Escape($Stem))-\d+\.\d+\.\d+-image\.txt$"; label = "Container image manifest" })
  }
  return @(
    [pscustomobject][ordered]@{ pattern = '(?i)\.msi$'; label = "Windows MSI installer" },
    [pscustomobject][ordered]@{ pattern = '(?i)(?:setup|installer).*\.exe$'; label = "Windows executable installer" },
    [pscustomobject][ordered]@{ pattern = '(?i)(?:x64|x86_64).*\.dmg$'; label = "macOS Intel DMG" },
    [pscustomobject][ordered]@{ pattern = '(?i)(?:aarch64|arm64).*\.dmg$'; label = "macOS Apple Silicon DMG" },
    [pscustomobject][ordered]@{ pattern = '(?i)\.AppImage$'; label = "Linux AppImage" },
    [pscustomobject][ordered]@{ pattern = '(?i)\.(?:deb|rpm)$'; label = "Linux package" }
  )
}

function Get-ExpectedAssets($Profile, [string]$Stem) {
  if ($Profile.ProjectType -eq "node") { return @("$Stem-$($Profile.Version).tgz") }
  if ($Profile.ProjectType -eq "go") {
    return @(
      "$Stem-windows-amd64.exe", "$Stem-windows-arm64.exe",
      "$Stem-linux-amd64", "$Stem-linux-arm64",
      "$Stem-darwin-amd64", "$Stem-darwin-arm64"
    )
  }
  if ($Profile.ProjectType -eq "python") {
    $pythonStem = $Stem.Replace("-", "_")
    return @("$Stem-$($Profile.Version).tar.gz", "$pythonStem-$($Profile.Version)-py3-none-any.whl")
  }
  if ($Profile.ProjectType -eq "rust") { return @("$Stem-$($Profile.Version).crate") }
  if ($Profile.ProjectType -eq "dotnet") { return @("$Stem.$($Profile.Version).nupkg") }
  if ($Profile.ProjectType -eq "java") { return @("$Stem-$($Profile.Version).jar") }
  if ($Profile.ProjectType -eq "cmake" -or $Profile.ProjectType -eq "electron") {
    return @(
      "$Stem-windows-x64.zip", "$Stem-windows-arm64.zip",
      "$Stem-linux-x64.zip", "$Stem-linux-arm64.zip",
      "$Stem-macos-x64.zip", "$Stem-macos-arm64.zip"
    )
  }
  if ($Profile.ProjectType -eq "flutter") {
    return @(
      "$Stem-android-apk.apk", "$Stem-android-aab.aab", "$Stem-windows-x64.zip",
      "$Stem-linux-x64.tar.gz", "$Stem-macos-x64.zip", "$Stem-macos-arm64.zip", "$Stem-web.zip"
    )
  }
  if ($Profile.ProjectType -eq "android") { return @("$Stem-$($Profile.Version).apk", "$Stem-$($Profile.Version).aab") }
  if ($Profile.ProjectType -eq "docker") { return @("$Stem-$($Profile.Version)-image.txt") }
  return @(
    "${Stem}_$($Profile.Version)_x64_en-US.msi",
    "${Stem}_$($Profile.Version)_x64-setup.exe",
    "${Stem}_$($Profile.Version)_x64.dmg",
    "${Stem}_$($Profile.Version)_aarch64.dmg",
    "${Stem}_$($Profile.Version)_amd64.AppImage",
    "${Stem}_$($Profile.Version)_amd64.deb"
  )
}

function New-GenerationBundle(
  $Profile,
  [string]$SelectedWorkflowPath = $WorkflowPath,
  [bool]$ManagedWorkflow = $true
) {
  $defaults = Get-RepositoryDefaults
  $stem = ConvertTo-ArtifactStem $Profile.ProjectName
  $updates = @()
  $bootstrapCommands = @()
  $bootstrapInputs = @()
  $bootstrapRequiredPaths = @()
  $localCommands = $null
  $commands = @()
  $artifacts = @()
  $additionalFiles = @()
  $readPath = $Profile.VersionSource
  $readPattern = $null

  if ($Profile.ProjectType -eq "node") {
    $readPattern = '"version"\s*:\s*"(?<version>\d+\.\d+\.\d+)"'
    $updates += New-VersionUpdate "package.json" '("version"\s*:\s*")\d+\.\d+\.\d+(")' '${1}{version}$2'
    Add-ExistingVersionUpdate ([ref]$updates) "package-lock.json" '(?ms)\A(\s*\{.{0,1000}?"version"\s*:\s*")\d+\.\d+\.\d+(")' '${1}{version}$2'
    Add-ExistingVersionUpdate ([ref]$updates) "package-lock.json" '(?ms)(""\s*:\s*\{[^{}]*?"version"\s*:\s*")\d+\.\d+\.\d+(")' '${1}{version}$2'
    $bootstrapCommands += [pscustomobject][ordered]@{ name = "Install dependencies"; command = $Profile.Manager.Install }
    $bootstrapInputs += @("package.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lock", "bun.lockb") | Where-Object {
      Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot $_)
    }
    $bootstrapRequiredPaths += "node_modules"
    if (Test-PackageScript $Profile.Package "test") {
      $commands += [pscustomobject][ordered]@{ name = "Tests"; command = Get-PackageCommand $Profile.Manager.Name "test" }
    }
    if (Test-PackageScript $Profile.Package "build") {
      $commands += [pscustomobject][ordered]@{ name = "Build"; command = Get-PackageCommand $Profile.Manager.Name "build" }
    }
    $commands += [pscustomobject][ordered]@{ name = "Pack"; command = "if not exist dist mkdir dist && npm pack --pack-destination dist" }
    $artifacts += [pscustomobject][ordered]@{ source = "dist/$Stem-{version}.tgz"; sha256 = $true }
  }
  elseif ($Profile.ProjectType -eq "electron") {
    $readPattern = '"version"\s*:\s*"(?<version>\d+\.\d+\.\d+)"'
    $updates += New-VersionUpdate "package.json" '("version"\s*:\s*")\d+\.\d+\.\d+(")' '${1}{version}$2'
    Add-ExistingVersionUpdate ([ref]$updates) "package-lock.json" '(?ms)\A(\s*\{.{0,1000}?"version"\s*:\s*")\d+\.\d+\.\d+(")' '${1}{version}$2'
    Add-ExistingVersionUpdate ([ref]$updates) "package-lock.json" '(?ms)(""\s*:\s*\{[^{}]*?"version"\s*:\s*")\d+\.\d+\.\d+(")' '${1}{version}$2'
    $bootstrapCommands += [pscustomobject][ordered]@{ name = "Install dependencies"; command = $Profile.Manager.Install }
    $bootstrapInputs += @("package.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lock", "bun.lockb") | Where-Object {
      Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot $_)
    }
    $bootstrapRequiredPaths += "node_modules"
    if (Test-PackageScript $Profile.Package "test") {
      $commands += [pscustomobject][ordered]@{ name = "Tests"; command = Get-PackageCommand $Profile.Manager.Name "test" }
    }
    $commands += [pscustomobject][ordered]@{ name = "Build Electron packages"; command = $Profile.ElectronBuildCommand }
  }
  elseif ($Profile.ProjectType -eq "tauri") {
    $readPattern = '"version"\s*:\s*"(?<version>\d+\.\d+\.\d+)"'
    Add-ExistingVersionUpdate ([ref]$updates) "src-tauri/tauri.conf.json" '("version"\s*:\s*")\d+\.\d+\.\d+(")' '${1}{version}$2'
    Add-ExistingVersionUpdate ([ref]$updates) "package.json" '("version"\s*:\s*")\d+\.\d+\.\d+(")' '${1}{version}$2'
    Add-ExistingVersionUpdate ([ref]$updates) "package-lock.json" '(?ms)\A(\s*\{.{0,1000}?"version"\s*:\s*")\d+\.\d+\.\d+(")' '${1}{version}$2'
    Add-ExistingVersionUpdate ([ref]$updates) "package-lock.json" '(?ms)(""\s*:\s*\{[^{}]*?"version"\s*:\s*")\d+\.\d+\.\d+(")' '${1}{version}$2'
    $cargoPattern = '(?ms)(^\[package\]\s*(?:(?!^\[).)*?^version\s*=\s*")\d+\.\d+\.\d+(")'
    Add-ExistingVersionUpdate ([ref]$updates) "src-tauri/Cargo.toml" $cargoPattern '${1}{version}$2'
    $cargoText = [IO.File]::ReadAllText((Join-Path $script:ResolvedRepositoryRoot "src-tauri\Cargo.toml"))
    $cargoNameMatch = [regex]::Match($cargoText, '(?ms)^\[package\]\s*(?:(?!^\[).)*?^name\s*=\s*"(?<name>[^"]+)"')
    if ($cargoNameMatch.Success) {
      $cargoName = [regex]::Escape($cargoNameMatch.Groups["name"].Value)
      $lockPattern = '(?ms)(^\[\[package\]\]\s*(?:(?!^\[\[package\]\]).)*?^name\s*=\s*"' + $cargoName + '"\s*(?:(?!^\[\[package\]\]).)*?^version\s*=\s*")\d+\.\d+\.\d+(")'
      Add-ExistingVersionUpdate ([ref]$updates) "src-tauri/Cargo.lock" $lockPattern '${1}{version}$2'
    }
    if ($Profile.Package) {
      $bootstrapCommands += [pscustomobject][ordered]@{ name = "Install dependencies"; command = $Profile.Manager.Install }
      $bootstrapInputs += @("package.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lock", "bun.lockb", "src-tauri/Cargo.toml", "src-tauri/Cargo.lock") | Where-Object {
        Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot $_)
      }
      $bootstrapRequiredPaths += "node_modules"
      if (Test-PackageScript $Profile.Package "test") {
        $commands += [pscustomobject][ordered]@{ name = "Tests"; command = Get-PackageCommand $Profile.Manager.Name "test" }
      }
      $commands += [pscustomobject][ordered]@{ name = "Build installers"; command = Get-PackageCommand $Profile.Manager.Name "tauri build" }
      $localCommands = @($commands | Where-Object { $_.name -ne "Build installers" })
      $localCommands += [pscustomobject][ordered]@{ name = "Build local program"; command = Get-TauriLocalBuildCommand $Profile.Manager.Name }
    }
    else {
      $commands += [pscustomobject][ordered]@{ name = "Build installers"; command = "cargo tauri build" }
      $localCommands = @([pscustomobject][ordered]@{ name = "Build local program"; command = "cargo tauri build --no-bundle" })
      $bootstrapInputs += @("src-tauri/Cargo.toml", "src-tauri/Cargo.lock") | Where-Object {
        Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot $_)
      }
    }
  }
  elseif ($Profile.ProjectType -eq "go") {
    $readPattern = '(?m)^(?<version>\d+\.\d+\.\d+)\s*$'
    $updates += New-VersionUpdate "VERSION" '(?m)^\d+\.\d+\.\d+\s*$' '{version}'
    if ($Profile.NeedsVersionFile) {
      $additionalFiles += [pscustomobject]@{ RelativePath = "VERSION"; Content = "$($Profile.Version)`n" }
    }
    $commands += [pscustomobject][ordered]@{ name = "Tests"; command = "go test ./..." }
    $commands += [pscustomobject][ordered]@{ name = "Build Windows"; command = "if not exist dist mkdir dist && go build -trimpath -o dist\$Stem.exe $($Profile.BuildPath)" }
    $artifacts += [pscustomobject][ordered]@{ source = "dist/$Stem.exe"; sha256 = $true }
  }
  elseif ($Profile.ProjectType -eq "flutter") {
    $readPattern = $Profile.VersionReadPattern
    $updates += New-VersionUpdate $Profile.VersionSource $Profile.VersionUpdatePattern '${1}{version}'
    $bootstrapCommands += [pscustomobject][ordered]@{ name = "Install dependencies"; command = "flutter pub get" }
    $bootstrapInputs += @("pubspec.yaml", "pubspec.lock") | Where-Object {
      Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot $_)
    }
    $bootstrapRequiredPaths += ".dart_tool/package_config.json"
    if ($Profile.HasTests) { $commands += [pscustomobject][ordered]@{ name = "Tests"; command = "flutter test" } }
    $commands += [pscustomobject][ordered]@{ name = "Build Windows"; command = "flutter build windows --release" }
  }
  elseif ($Profile.ProjectType -eq "android") {
    $readPattern = $Profile.VersionReadPattern
    $updates += New-VersionUpdate $Profile.VersionSource $Profile.VersionUpdatePattern '${1}{version}$2'
    $commands += [pscustomobject][ordered]@{ name = "Test and package Android"; command = $Profile.AndroidLocalBuild }
  }
  elseif ($Profile.ProjectType -eq "cmake") {
    if ($Profile.NeedsVersionFile) {
      $readPattern = '(?m)^(?<version>\d+\.\d+\.\d+)\s*$'
      $updates += New-VersionUpdate "VERSION" '(?m)^\d+\.\d+\.\d+\s*$' '{version}'
      $additionalFiles += [pscustomobject]@{ RelativePath = "VERSION"; Content = "$($Profile.Version)`n" }
    }
    else {
      $projectName = [regex]::Escape($Profile.ProjectName)
      $readPattern = '(?is)\bproject\s*\(\s*' + $projectName + '(?:(?!\)).)*?\bVERSION\s+(?<version>\d+\.\d+\.\d+)'
      $updatePattern = '(?is)(\bproject\s*\(\s*' + $projectName + '(?:(?!\)).)*?\bVERSION\s+)\d+\.\d+\.\d+'
      $updates += New-VersionUpdate "CMakeLists.txt" $updatePattern '${1}{version}'
    }
    $commands += [pscustomobject][ordered]@{ name = "Configure"; command = "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release" }
    $commands += [pscustomobject][ordered]@{ name = "Build"; command = "cmake --build build --config Release --parallel" }
    $commands += [pscustomobject][ordered]@{ name = "Tests"; command = "ctest --test-dir build -C Release --output-on-failure" }
  }
  elseif ($Profile.ProjectType -eq "docker") {
    $readPattern = '(?m)^(?<version>\d+\.\d+\.\d+)\s*$'
    $updates += New-VersionUpdate "VERSION" '(?m)^\d+\.\d+\.\d+\s*$' '{version}'
    if ($Profile.NeedsVersionFile) {
      $additionalFiles += [pscustomobject]@{ RelativePath = "VERSION"; Content = "$($Profile.Version)`n" }
    }
    $commands += [pscustomobject][ordered]@{ name = "Build container"; command = "docker build --file `"$($Profile.BuildPath)`" --tag `"${Stem}:{version}`" ." }
  }
  elseif ($Profile.ProjectType -eq "python") {
    $readPattern = $Profile.VersionReadPattern
    $updates += New-VersionUpdate $Profile.VersionSource $Profile.VersionUpdatePattern '${1}{version}$2'
    if ($Profile.PackageManager -eq "uv") {
      $bootstrapCommands += [pscustomobject][ordered]@{ name = "Install dependencies"; command = "python -m pip install uv && uv sync --all-extras" }
      if ($Profile.HasTests) { $commands += [pscustomobject][ordered]@{ name = "Tests"; command = "uv run pytest" } }
      $commands += [pscustomobject][ordered]@{ name = "Build distributions"; command = "uv build" }
    }
    elseif ($Profile.PackageManager -eq "poetry") {
      $bootstrapCommands += [pscustomobject][ordered]@{ name = "Install dependencies"; command = "python -m pip install poetry && poetry install" }
      if ($Profile.HasTests) { $commands += [pscustomobject][ordered]@{ name = "Tests"; command = "poetry run pytest" } }
      $commands += [pscustomobject][ordered]@{ name = "Build distributions"; command = "poetry build" }
    }
    else {
      $installCommand = "python -m pip install --upgrade build && python -m pip install -e ."
      if ($Profile.HasTests) { $installCommand += " && python -m pip install pytest" }
      $bootstrapCommands += [pscustomobject][ordered]@{ name = "Install dependencies"; command = $installCommand }
      if ($Profile.HasTests) { $commands += [pscustomobject][ordered]@{ name = "Tests"; command = "python -m pytest" } }
      $commands += [pscustomobject][ordered]@{ name = "Build distributions"; command = "python -m build" }
    }
    $bootstrapInputs += @("pyproject.toml", "uv.lock", "poetry.lock", "requirements.txt") | Where-Object {
      Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot $_)
    }
  }
  elseif ($Profile.ProjectType -eq "rust") {
    $readPattern = '(?ms)^\[package\]\s*(?:(?!^\[).)*?^version\s*=\s*"(?<version>\d+\.\d+\.\d+)"'
    $cargoPattern = '(?ms)(^\[package\]\s*(?:(?!^\[).)*?^version\s*=\s*")\d+\.\d+\.\d+(")'
    $updates += New-VersionUpdate "Cargo.toml" $cargoPattern '${1}{version}$2'
    $cargoName = [regex]::Escape($Profile.ProjectName)
    $lockPattern = '(?ms)(^\[\[package\]\]\s*(?:(?!^\[\[package\]\]).)*?^name\s*=\s*"' + $cargoName + '"\s*(?:(?!^\[\[package\]\]).)*?^version\s*=\s*")\d+\.\d+\.\d+(")'
    Add-ExistingVersionUpdate ([ref]$updates) "Cargo.lock" $lockPattern '${1}{version}$2'
    $commands += [pscustomobject][ordered]@{ name = "Tests"; command = "cargo test --all" }
    $commands += [pscustomobject][ordered]@{ name = "Package crate"; command = "cargo package --allow-dirty" }
    $artifacts += [pscustomobject][ordered]@{ source = "target/package/$Stem-{version}.crate"; sha256 = $true }
  }
  elseif ($Profile.ProjectType -eq "dotnet") {
    if ($Profile.NeedsVersionFile) {
      $readPattern = '(?m)^(?<version>\d+\.\d+\.\d+)\s*$'
      $updates += New-VersionUpdate "VERSION" '(?m)^\d+\.\d+\.\d+\s*$' '{version}'
      $additionalFiles += [pscustomobject]@{ RelativePath = "VERSION"; Content = "$($Profile.Version)`n" }
    }
    else {
      $element = [regex]::Escape([string]$Profile.VersionElement)
      $readPattern = "(?s)<$element>\s*(?<version>\d+\.\d+\.\d+)\s*</$element>"
      $updatePattern = "(?s)(<$element>\s*)\d+\.\d+\.\d+(\s*</$element>)"
      $updates += New-VersionUpdate $Profile.VersionSource $updatePattern '${1}{version}$2'
    }
    $bootstrapCommands += [pscustomobject][ordered]@{ name = "Restore"; command = "dotnet restore `"$($Profile.BuildPath)`"" }
    $bootstrapInputs += @($Profile.BuildPath, "packages.lock.json") | Where-Object {
      Test-Path -LiteralPath (Join-Path $script:ResolvedRepositoryRoot $_)
    }
    $projectDirectory = Split-Path -Parent $Profile.BuildPath
    $bootstrapRequiredPaths += if ($projectDirectory) { "$projectDirectory/obj/project.assets.json" } else { "obj/project.assets.json" }
    $commands += [pscustomobject][ordered]@{ name = "Tests"; command = "dotnet test `"$($Profile.BuildPath)`" --no-restore --configuration Release" }
    $commands += [pscustomobject][ordered]@{ name = "Pack"; command = "dotnet pack `"$($Profile.BuildPath)`" --no-restore --configuration Release -p:PackageVersion={version} --output dist" }
    $artifacts += [pscustomobject][ordered]@{ source = "dist/$Stem.{version}.nupkg"; sha256 = $true }
  }
  elseif ($Profile.ProjectType -eq "java") {
    $readPattern = $Profile.VersionReadPattern
    $updates += New-VersionUpdate $Profile.VersionSource $Profile.VersionUpdatePattern '${1}{version}$2'
    $commands += [pscustomobject][ordered]@{ name = "Test and package"; command = $Profile.JavaLocalBuild }
  }
  else {
    throw "No generation strategy for project type: $($Profile.ProjectType)"
  }

  if ($null -eq $localCommands) { $localCommands = @($commands) }

  $templateName = "$($Profile.ProjectType)-v1"
  $requiredAssets = @(Get-RequiredAssets $Profile.ProjectType $stem)
  $config = [pscustomobject][ordered]@{
    schemaVersion = 2
    projectType = $Profile.ProjectType
    automation = [pscustomobject][ordered]@{
      generator = $script:GeneratorName
      template = $templateName
      managedWorkflow = $ManagedWorkflow
      workflowFile = $SelectedWorkflowPath.Replace("\", "/")
    }
    projectName = $Profile.ProjectName
    branch = $defaults.Branch
    remote = $defaults.Remote
    tagPrefix = "v"
    version = [pscustomobject][ordered]@{
      read = [pscustomobject][ordered]@{ path = $readPath; pattern = $readPattern }
      updates = @($updates)
    }
    prepare = [pscustomobject][ordered]@{
      parallel = $false
      localOutputDirectory = "output"
      bootstrapInputs = @($bootstrapInputs | Sort-Object -Unique)
      bootstrapRequiredPaths = @($bootstrapRequiredPaths | Sort-Object -Unique)
      bootstrapCommands = @($bootstrapCommands)
      localCommands = @($localCommands)
      commands = @($commands)
      artifacts = @($artifacts)
    }
    releaseNotes = Get-ReleaseNotesConfig
    publish = [pscustomobject][ordered]@{
      workflow = Get-WorkflowConfig
      release = [pscustomobject][ordered]@{
        mode = "publish-draft"
        title = "{projectName} {tag}"
        requireDraft = $true
        requiredAssets = $requiredAssets
      }
    }
  }

  $expectedAssets = @(Get-ExpectedAssets $Profile $stem)
  $testStep = ""
  $buildStep = ""
  $managerSetup = ""
  $installCommand = "echo No package.json; skipping frontend dependencies"
  $pythonInstallCommand = "python -m pip install --upgrade build && python -m pip install -e ."
  $pythonBuildCommand = "python -m build"
  if ($Profile.Package) {
    $managerSetup = $Profile.Manager.WorkflowSetup
    $installCommand = $Profile.Manager.Install
    if (Test-PackageScript $Profile.Package "test") {
      $testStep = "      - name: Test`n        run: $(Get-PackageCommand $Profile.Manager.Name 'test')"
    }
    if (Test-PackageScript $Profile.Package "build") {
      $buildStep = "      - name: Build`n        run: $(Get-PackageCommand $Profile.Manager.Name 'build')"
    }
  }
  if ($Profile.ProjectType -eq "python") {
    if ($Profile.PackageManager -eq "uv") {
      $pythonInstallCommand = "python -m pip install uv && uv sync --all-extras"
      $pythonBuildCommand = "uv build"
      if ($Profile.HasTests) { $testStep = "      - name: Test`n        run: uv run pytest" }
    }
    elseif ($Profile.PackageManager -eq "poetry") {
      $pythonInstallCommand = "python -m pip install poetry && poetry install"
      $pythonBuildCommand = "poetry build"
      if ($Profile.HasTests) { $testStep = "      - name: Test`n        run: poetry run pytest" }
    }
    elseif ($Profile.HasTests) {
      $testStep = "      - name: Test`n        run: python -m pip install pytest && python -m pytest"
    }
  }
  $tokens = @{
    PROJECT_NAME = $Profile.ProjectName.Replace('"', '')
    ARTIFACT_STEM = $stem
    BUILD_PATH = [string]$Profile.BuildPath
    PACKAGE_MANAGER_SETUP = $managerSetup
    INSTALL_COMMAND = $installCommand
    TEST_STEP = $testStep
    BUILD_STEP = $buildStep
    PYTHON_INSTALL_COMMAND = $pythonInstallCommand
    PYTHON_BUILD_COMMAND = $pythonBuildCommand
    DOTNET_PROJECT = [string]$Profile.BuildPath
    DOTNET_VERSION = [string](Get-OptionalProperty $Profile "DotNetVersion" "8.0.x")
    JAVA_CACHE = [string](Get-OptionalProperty $Profile "JavaCache" "maven")
    JAVA_BUILD_COMMAND = [string](Get-OptionalProperty $Profile "JavaWorkflowBuild" "mvn -B test package")
    JAVA_ARTIFACT_DIRECTORY = [string](Get-OptionalProperty $Profile "JavaArtifactDirectory" "target")
    CMAKE_TARGET = [string](Get-OptionalProperty $Profile "CMakeTarget" "app")
    ANDROID_MODULE = [string]$Profile.BuildPath
    ELECTRON_BUILD_COMMAND = [string](Get-OptionalProperty $Profile "ElectronBuildCommand" "npm run dist")
    ELECTRON_OUTPUT = [string](Get-OptionalProperty $Profile "ElectronOutput" "dist")
    DOCKERFILE = [string]$Profile.BuildPath
    EXPECTED_ASSET = $expectedAssets[0]
    EXPECTED_ASSET_COMMENTS = (($expectedAssets | ForEach-Object { "# Expected asset: $_" }) -join "`n")
  }
  return [pscustomobject]@{
    Config = $config
    TemplateName = $templateName
    TemplateFile = Join-Path (Split-Path -Parent $PSScriptRoot) "assets\workflows\$($Profile.ProjectType).yml"
    Tokens = $tokens
    AdditionalFiles = @($additionalFiles)
  }
}

function Render-Template([string]$Path, [hashtable]$Tokens) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "Workflow template not found: $Path" }
  $content = [IO.File]::ReadAllText($Path)
  foreach ($entry in $Tokens.GetEnumerator()) {
    $content = $content.Replace("{{$($entry.Key)}}", [string]$entry.Value)
  }
  if ($content -match '\{\{[A-Z][A-Z0-9_]*\}\}') {
    throw "Workflow template contains unresolved token: $($Matches[0])"
  }
  return $content
}

function Assert-ManagedConfigOrAbsent([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return }
  $existing = Read-JsonFile $Path "Existing release config"
  $automation = Get-OptionalProperty $existing "automation"
  if (-not (Test-ManagedGeneratorName ([string](Get-OptionalProperty $automation "generator" "")))) {
    throw "Refusing to overwrite human-managed release config: $Path"
  }
}

function Test-ManagedGeneratorName([string]$Name) {
  return $Name -eq $script:GeneratorName -or $Name -in $script:LegacyGeneratorNames
}

function Test-ManagedWorkflowContent([string]$Content) {
  foreach ($marker in @($script:WorkflowMarker) + $script:LegacyWorkflowMarkers) {
    if ($Content.StartsWith($marker, [StringComparison]::Ordinal)) { return $true }
  }
  return $false
}

function Assert-ManagedWorkflowOrAbsent([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return }
  $content = [IO.File]::ReadAllText($Path)
  if (-not (Test-ManagedWorkflowContent $content)) {
    throw "Refusing to overwrite human-managed workflow: $Path"
  }
}

function Test-ManagedWorkflow([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return $false }
  return Test-ManagedWorkflowContent ([IO.File]::ReadAllText($Path))
}

function Assert-CompatibleWorkflowContent([string]$Content, [string]$ProjectType) {
  $workflowName = Get-WorkflowName $Content
  if ($Content -notmatch '(?ms)^on:\s*\r?\n\s+push:\s*\r?\n\s+tags:') {
    throw "Existing workflow is not compatible: tag push trigger is missing"
  }
  if ($Content -notmatch '(?ms)^permissions:\s*\r?\n\s+contents:\s*write\s*$') {
    throw "Existing workflow is not compatible: contents write permission is missing"
  }
  if ($Content -notmatch '(?i)(releaseDraft:\s*true|gh\s+release\s+create[^\r\n]*(?:\r?\n[^\r\n]*)*?--draft)') {
    throw "Existing workflow is not compatible: draft Release creation is missing"
  }
  if ($ProjectType -eq "docker") {
    if ($Content -notmatch '(?ms)^permissions:\s*.*?^\s+packages:\s*write\s*$') {
      throw "Existing Docker workflow is not compatible: packages write permission is missing"
    }
    if ($Content -notmatch 'docker/build-push-action@v7' -or $Content -notmatch '(?m)^\s+push:\s*true\s*$') {
      throw "Existing Docker workflow is not compatible: image push is missing"
    }
  }
  return $workflowName
}

function Write-AtomicUtf8([string]$Path, [string]$Content) {
  $directory = Split-Path -Parent $Path
  if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
  }
  $temporary = Join-Path $directory ((Split-Path -Leaf $Path) + ".tmp." + [guid]::NewGuid().ToString("N"))
  $backup = Join-Path $directory ((Split-Path -Leaf $Path) + ".bak." + [guid]::NewGuid().ToString("N"))
  try {
    [IO.File]::WriteAllText($temporary, $Content, [Text.UTF8Encoding]::new($false))
    if (Test-Path -LiteralPath $Path -PathType Leaf) {
      [IO.File]::Replace($temporary, $Path, $backup)
    }
    else {
      [IO.File]::Move($temporary, $Path)
    }
  }
  finally {
    if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force }
    if (Test-Path -LiteralPath $backup) { Remove-Item -LiteralPath $backup -Force }
  }
}

function Invoke-Generate($Profile) {
  $configFile = Resolve-RepositoryFile $ConfigPath
  $selectedWorkflowPath = $WorkflowPath
  $workflowFile = Resolve-RepositoryFile $selectedWorkflowPath
  $reuseHumanWorkflow = $false
  $humanWorkflowName = $null

  if ((Test-Path -LiteralPath $workflowFile -PathType Leaf) -and -not (Test-ManagedWorkflow $workflowFile)) {
    if ($ExistingWorkflowPolicy -eq "CreateSeparate") {
      if ($SeparateWorkflowPath.Replace("\", "/") -eq $WorkflowPath.Replace("\", "/")) {
        throw "Separate workflow path must differ from the existing workflow path"
      }
      $selectedWorkflowPath = $SeparateWorkflowPath
      $workflowFile = Resolve-RepositoryFile $selectedWorkflowPath
      if ((Test-Path -LiteralPath $workflowFile -PathType Leaf) -and -not (Test-ManagedWorkflow $workflowFile)) {
        throw "Refusing to overwrite human-managed separate workflow: $workflowFile"
      }
      Write-Host "Preserving human workflow; using separate release workflow: $selectedWorkflowPath"
    }
    elseif ($ExistingWorkflowPolicy -eq "ReuseCompatible") {
      $humanWorkflowName = Assert-CompatibleWorkflowContent ([IO.File]::ReadAllText($workflowFile)) $Profile.ProjectType
      $reuseHumanWorkflow = $true
      Write-Host "Reusing compatible human-managed workflow: $selectedWorkflowPath"
    }
    else {
      throw "Refusing to overwrite human-managed workflow: $workflowFile"
    }
  }

  $bundle = New-GenerationBundle $Profile $selectedWorkflowPath (-not $reuseHumanWorkflow)
  if ($reuseHumanWorkflow) {
    $bundle.Config.publish.workflow.name = $humanWorkflowName
  }
  $configContent = ($bundle.Config | ConvertTo-Json -Depth 20) + "`n"
  $workflowContent = $null
  if (-not $reuseHumanWorkflow) {
    $workflowContent = Render-Template $bundle.TemplateFile $bundle.Tokens
    if (-not $workflowContent.EndsWith("`n")) { $workflowContent += "`n" }
  }

  Assert-ManagedConfigOrAbsent $configFile
  if (-not $reuseHumanWorkflow) {
    Assert-ManagedWorkflowOrAbsent $workflowFile
  }
  foreach ($additional in $bundle.AdditionalFiles) {
    $additionalPath = Resolve-RepositoryFile $additional.RelativePath
    if (
      (Test-Path -LiteralPath $additionalPath -PathType Leaf) -and
      [IO.File]::ReadAllText($additionalPath) -cne $additional.Content
    ) {
      throw "Refusing to overwrite existing generated support file: $additionalPath"
    }
  }

  $desired = @([pscustomobject]@{ Path = $configFile; Content = $configContent })
  if (-not $reuseHumanWorkflow) {
    $desired += [pscustomobject]@{ Path = $workflowFile; Content = $workflowContent }
  }
  foreach ($additional in $bundle.AdditionalFiles) {
    $desired += [pscustomobject]@{ Path = Resolve-RepositoryFile $additional.RelativePath; Content = $additional.Content }
  }
  foreach ($file in $desired) {
    if ((Test-Path -LiteralPath $file.Path -PathType Leaf) -and [IO.File]::ReadAllText($file.Path) -ceq $file.Content) {
      Write-Host "Unchanged: $($file.Path)"
    }
    else {
      Write-AtomicUtf8 $file.Path $file.Content
      Write-Host "Generated: $($file.Path)"
    }
  }
  Invoke-Validate
}

function Invoke-GenerateLocal($Profile) {
  $configFile = Resolve-RepositoryFile $ConfigPath
  $bundle = New-GenerationBundle $Profile $WorkflowPath $false
  $bundle.Config.automation | Add-Member -NotePropertyName localOnly -NotePropertyValue $true -Force
  $bundle.Config.publish.workflow = $null
  $bundle.Config.publish.release.mode = "none"
  $configContent = ($bundle.Config | ConvertTo-Json -Depth 20) + "`n"

  Assert-ManagedConfigOrAbsent $configFile
  foreach ($additional in $bundle.AdditionalFiles) {
    $additionalPath = Resolve-RepositoryFile $additional.RelativePath
    if (
      (Test-Path -LiteralPath $additionalPath -PathType Leaf) -and
      [IO.File]::ReadAllText($additionalPath) -cne $additional.Content
    ) {
      throw "Refusing to overwrite existing generated support file: $additionalPath"
    }
  }

  $desired = @([pscustomobject]@{ Path = $configFile; Content = $configContent })
  foreach ($additional in $bundle.AdditionalFiles) {
    $desired += [pscustomobject]@{ Path = Resolve-RepositoryFile $additional.RelativePath; Content = $additional.Content }
  }
  foreach ($file in $desired) {
    if ((Test-Path -LiteralPath $file.Path -PathType Leaf) -and [IO.File]::ReadAllText($file.Path) -ceq $file.Content) {
      Write-Host "Unchanged: $($file.Path)"
    }
    else {
      Write-AtomicUtf8 $file.Path $file.Content
      Write-Host "Generated local build config: $($file.Path)"
    }
  }
  Invoke-Validate
}

function Get-WorkflowName([string]$Content) {
  $match = [regex]::Match($Content, '(?m)^name:\s*(?<name>[^\r\n#]+)')
  if (-not $match.Success) { throw "Workflow does not declare a name" }
  return $match.Groups["name"].Value.Trim().Trim('"').Trim("'")
}

function Invoke-Validate {
  $configFile = Resolve-RepositoryFile $ConfigPath
  if (-not (Test-Path -LiteralPath $configFile -PathType Leaf)) { throw "Release config not found: $configFile" }
  $configText = [IO.File]::ReadAllText($configFile)
  if ($configText -match '\{\{[A-Z][A-Z0-9_]*\}\}') { throw "Release config contains unresolved token: $($Matches[0])" }
  $config = Read-JsonFile $configFile "Release config"
  $schemaVersion = [int](Get-RequiredProperty $config "schemaVersion" "root")
  if ($schemaVersion -notin @(1, 2)) { throw "Unsupported release config schemaVersion: $schemaVersion" }
  if ($schemaVersion -eq 2) {
    $configuredProjectType = [string](Get-RequiredProperty $config "projectType" "root")
    if ($configuredProjectType -notin @("tauri", "node", "go", "python", "rust", "dotnet", "java", "cmake", "flutter", "android", "electron", "docker")) { throw "Unsupported projectType: $configuredProjectType" }
  }
  foreach ($name in @("projectName", "branch", "remote")) { Get-RequiredProperty $config $name "root" | Out-Null }

  $version = Get-RequiredProperty $config "version" "root"
  $read = Get-RequiredProperty $version "read" "version"
  $readPath = [string](Get-RequiredProperty $read "path" "version.read")
  $readPattern = [string](Get-RequiredProperty $read "pattern" "version.read")
  try { $readRegex = [regex]::new($readPattern) } catch { throw "version.read.pattern is invalid: $($_.Exception.Message)" }
  if ($readRegex.GetGroupNames() -notcontains "version") { throw "version.read.pattern must contain a named 'version' capture group" }
  $versionFile = Resolve-RepositoryFile $readPath
  if (-not (Test-Path -LiteralPath $versionFile -PathType Leaf)) { throw "Version source not found: $versionFile" }
  $versionMatch = $readRegex.Match([IO.File]::ReadAllText($versionFile))
  if (-not $versionMatch.Success -or $versionMatch.Groups["version"].Value -notmatch '^\d+\.\d+\.\d+$') {
    throw "Version source does not match version.read.pattern: $readPath"
  }
  foreach ($update in @(Get-OptionalProperty $version "updates" @())) {
    $updatePath = [string](Get-RequiredProperty $update "path" "version.updates[]")
    $updateFile = Resolve-RepositoryFile $updatePath
    if (-not (Test-Path -LiteralPath $updateFile -PathType Leaf)) { throw "Version update file not found: $updateFile" }
    try { [regex]::new([string](Get-RequiredProperty $update "pattern" "version.updates[]")) | Out-Null }
    catch { throw "Invalid version update pattern for ${updatePath}: $($_.Exception.Message)" }
  }

  $publish = Get-RequiredProperty $config "publish" "root"
  $release = Get-RequiredProperty $publish "release" "publish"
  $releaseMode = [string](Get-RequiredProperty $release "mode" "publish.release")
  if ($releaseMode -notin @("publish-draft", "create", "none")) { throw "Unsupported publish.release.mode: $releaseMode" }
  $workflowConfig = Get-OptionalProperty $publish "workflow"
  $automation = Get-OptionalProperty $config "automation"
  $managed = [bool](Get-OptionalProperty $automation "managedWorkflow" $false)
  if ($schemaVersion -eq 2 -and $managed) {
    if (-not (Test-ManagedGeneratorName ([string](Get-OptionalProperty $automation "generator" "")))) { throw "Managed config generator is not recognized" }
    Get-RequiredProperty $automation "template" "automation" | Out-Null
    Get-RequiredProperty $automation "workflowFile" "automation" | Out-Null
  }

  if ($workflowConfig -or $managed) {
    $configuredWorkflowPath = [string](Get-OptionalProperty $automation "workflowFile" $WorkflowPath)
    $workflowFile = Resolve-RepositoryFile $configuredWorkflowPath
    if (-not (Test-Path -LiteralPath $workflowFile -PathType Leaf)) { throw "Release workflow not found: $workflowFile" }
    $workflow = [IO.File]::ReadAllText($workflowFile)
    if ($workflow -match '\{\{[A-Z][A-Z0-9_]*\}\}') { throw "Workflow contains unresolved token: $($Matches[0])" }
    if ($managed) {
      if (-not (Test-ManagedWorkflowContent $workflow)) { throw "Managed workflow marker is missing" }
      $template = [regex]::Escape([string]$automation.template)
      if ($workflow -notmatch "(?m)^# Template: $template\s*$") { throw "Managed workflow template does not match config" }
    }
    if ($workflowConfig) {
      $expectedWorkflowName = [string](Get-RequiredProperty $workflowConfig "name" "publish.workflow")
      if ((Get-WorkflowName $workflow) -ne $expectedWorkflowName) { throw "Workflow name does not match publish.workflow.name" }
    }
    if ($workflow -notmatch '(?ms)^on:\s*\r?\n\s+push:\s*\r?\n\s+tags:') { throw "Workflow must use a tag push trigger" }
    if ($workflow -notmatch '(?ms)^permissions:\s*\r?\n\s+contents:\s*write\s*$') { throw "Workflow must grant contents: write" }
    if ($workflow -notmatch '(?i)(releaseDraft:\s*true|gh\s+release\s+create[^\r\n]*(?:\r?\n[^\r\n]*)*?--draft)') {
      throw "Workflow must create a draft GitHub Release"
    }
    if ($configuredProjectType -eq "docker") {
      if ($workflow -notmatch '(?ms)^permissions:\s*.*?^\s+packages:\s*write\s*$') { throw "Docker workflow must grant packages: write" }
      if ($workflow -notmatch 'docker/build-push-action@v7' -or $workflow -notmatch '(?m)^\s+push:\s*true\s*$') {
        throw "Docker workflow must push the generated image"
      }
    }

    $expectedAssets = @([regex]::Matches($workflow, '(?m)^# Expected asset:\s*(?<name>\S.+?)\s*$') | ForEach-Object { $_.Groups["name"].Value })
    $requiredAssets = @(Get-OptionalProperty $release "requiredAssets" @())
    if ($managed -and $expectedAssets.Count -eq 0) { throw "Managed workflow does not declare expected assets" }
    if ($managed -and $requiredAssets.Count -eq 0) { throw "Managed config does not declare required assets" }
    $compiledPatterns = @()
    foreach ($asset in $requiredAssets) {
      $pattern = [string](Get-RequiredProperty $asset "pattern" "publish.release.requiredAssets[]")
      try { $compiledPatterns += [regex]::new($pattern) } catch { throw "Invalid required asset pattern: $pattern" }
    }
    if ($expectedAssets.Count -gt 0) {
      foreach ($name in $expectedAssets) {
        if (-not @($compiledPatterns | Where-Object { $_.IsMatch($name) }).Count) { throw "Expected workflow asset is not covered by config: $name" }
      }
      foreach ($pattern in $compiledPatterns) {
        if (-not @($expectedAssets | Where-Object { $pattern.IsMatch($_) }).Count) { throw "Required asset pattern does not match a generated asset: $($pattern.ToString())" }
      }
    }
  }
  Write-Host "Valid release automation: $configFile"
}

if (-not (Test-Path -LiteralPath $RepositoryRoot -PathType Container)) { throw "Repository root not found: $RepositoryRoot" }
$script:ResolvedRepositoryRoot = Get-NormalizedPath (Resolve-Path -LiteralPath $RepositoryRoot).Path

if ($Mode -eq "Validate") {
  Invoke-Validate
}
else {
  $profile = Get-ProjectProfile $ProjectType
  if ($Mode -eq "Detect") {
    [pscustomobject][ordered]@{
      projectType = $profile.ProjectType
      projectName = $profile.ProjectName
      version = $profile.Version
      versionSource = $profile.VersionSource
      packageManager = $profile.PackageManager
      buildPath = $profile.BuildPath
    } | ConvertTo-Json -Depth 4
  }
  elseif ($Mode -eq "GenerateLocal") {
    Invoke-GenerateLocal $profile
  }
  else {
    Invoke-Generate $profile
  }
}
